<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoArena.Application\AlgoArena.Application.csproj" />
    <ProjectReference Include="..\AlgoArena.Domain\AlgoArena.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\Content\" />
    <Folder Include="Repositories\Lookups\" />
    <Folder Include="Repositories\Analytics\" />
    <Folder Include="Repositories\Submissions\" />
    <Folder Include="Repositories\Profiles\" />
    <Folder Include="Repositories\Identity\" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Identity" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

</Project>
