using AlgoArena.Domain.Common;
using AlgoArena.Domain.Entities.Analytics;
using AlgoArena.Domain.Entities.Audit;
using AlgoArena.Domain.Entities.Lookups;
using AlgoArena.Domain.Entities.Profiles;
using AlgoArena.Domain.Entities.Submissions;

namespace AlgoArena.Domain.Entities.Identity
{
    public sealed class User: AuditableEntity
    {
        /// <summary>
        /// Unique username used for login and identification.
        /// </summary>
        public string Username { get; set; } = string.Empty;

        /// <summary>
        /// User's email address.
        /// </summary>
        public string Email { get; set; } = string.Empty;

        /// <summary>
        /// Hashed password generated by ASP.NET Core Identity PasswordHasher.
        /// </summary>
        public string PasswordHash { get; set; } = string.Empty;

        /// <summary>
        /// Foreign key to Role.
        /// </summary>
        public Guid RoleId { get; set; }

        /// <summary>
        /// Foreign key to Account Status.
        /// </summary>
        public Guid AccountStatusId { get; set; }

        /// <summary>
        /// Date and time of the user's last successful login.
        /// </summary>
        public DateTime? LastLoginAt { get; set; }


        // Lookup Navigation
        public Role Role { get; set; } = null!;

        public AccountStatus AccountStatus { get; set; } = null!;


        // One-to-One Navigation
        public UserProfile UserProfile { get; set; } = null!;

        public ProfessionalDetail ProfessionalDetail { get; set; } = null!;

        public SocialMediaLink SocialMediaLink { get; set; } = null!;


        // One-to-Many (Collection) Navigation
        public ICollection<EducationDetail> EducationDetails { get; set; } = new List<EducationDetail>();
        
        public ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

        public ICollection<Submission> Submissions { get; set; } = new List<Submission>();

        public ICollection<UserProblem> UserProblems { get; set; } = new List<UserProblem>();

        public ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();
    }
}
