services:
  api:
    image: ${API_IMAGE}
    container_name: algoarena-api
    restart: unless-stopped

    ports:
      - "8081:8080"

    env_file:
      - .env

    environment:
      ASPNETCORE_URLS: http://+:8080