<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoArena.Domain\AlgoArena.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Submissions\" />
    <Folder Include="Features\Videos\" />
    <Folder Include="Features\Articles\" />
    <Folder Include="Features\Categories\" />
    <Folder Include="Features\Problems\" />
    <Folder Include="Features\Topics\" />
    <Folder Include="Features\Users\" />
    <Folder Include="Features\Authentication\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Behaviors\" />
    <Folder Include="Validators\" />
    <Folder Include="DTOs\" />
    <Folder Include="Common\" />
  </ItemGroup>

</Project>
