name: Backend CI

on:
  push:
    branches:
      # - main
      - deploy/test

  pull_request:
    branches:
      # - main
      - deploy/test

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AlgoArena

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: AlgoArena/global.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Build backend
        run: dotnet build AlgoArena.sln --configuration Release --no-restore